version: '3'
services:
  resizer:
    build:
      context: ./
      dockerfile: dockerization/resizer/Dockerfile
    restart: always
    volumes:
    - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt

    ports:
    - "127.0.0.1:8080:8080"

    environment:
    - RESIZER_SERVICE_HTTP_ADDRESS=:8080
    - RESIZER_SERVICE_CRAWLER_TIMEOUT=5s
    - RESIZER_SERVICE_RESIZER_FILTER=box